// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace JewelrySalesStoreData.Models;

public partial class OrderDetail
{
    public string OrderDetailId { get; set; }

    public Guid? OrderId { get; set; }

    public string Quantity { get; set; }

    public Guid? ProductId { get; set; }

    public string UnitPrice { get; set; }

    public Guid? TotalPrice { get; set; }

    public virtual Order Order { get; set; }

    public virtual Product Product { get; set; }
}